# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    permissions:
      contents: write
      
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: |
       dotnet build --configuration Release --no-restore
       dotnet publish -c Release -r win-x64 --output ./publish/win-x64  --self-contained true --no-restore
       dotnet publish -c Release -r win-x86 --output ./publish/win-x86  --self-contained true --no-restore
       dotnet publish -c Release -r win-arm64 --output ./publish/win-arm64  --self-contained true --no-restore
       dotnet publish -c Release -r osx-x64 --output ./publish/osx-x64  --self-contained true --no-restore
       dotnet publish -c Release -r osx-arm64 --output ./publish/osx-arm64  --self-contained true --no-restore
       dotnet publish -c Release -r linux-x64 --output ./publish/linux-x64  --self-contained true --no-restore
       dotnet publish -c Release -r linux-arm --output ./publish/linux-arm  --self-contained true --no-restore
       dotnet publish -c Release -r linux-arm64 --output ./publish/linux-arm64  --self-contained true --no-restore
       dotnet publish -c Release -r linux-musl-arm64 --output ./publish/linux-musl-arm64  --self-contained true --no-restore
       dotnet publish -c Release -r linux-musl-x64 --output ./publish/linux-musl-x64  --self-contained true --no-restore
       rm -f ./publish/*/*.pdb
       rm -f ./publish/*/*.xml
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: true
        title: "testcase-validator"
        files: |
          LICENSE
          publish/*/testcase-validator
