# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    permissions:
      contents: write
      
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: |
       dotnet build --configuration Release --no-restore
       dotnet publish -c Release -r win-x64 --output ./publish/win-x64/ --self-contained true
       dotnet publish -c Release -r win-x86 --output ./publish/win-x86/ --self-contained true
       dotnet publish -c Release -r win-arm64 --output ./publish/win-arm64/ --self-contained true
       dotnet publish -c Release -r osx-x64 --output ./publish/osx-x64/ --self-contained true
       dotnet publish -c Release -r osx-arm64 --output ./publish/osx-arm64/ --self-contained true
       dotnet publish -c Release -r linux-x64 --output ./publish/linux-x64/ --self-contained true
       dotnet publish -c Release -r linux-arm --output ./publish/linux-arm/ --self-contained true
       dotnet publish -c Release -r linux-arm64 --output ./publish/linux-arm64/ --self-contained true
       dotnet publish -c Release -r linux-musl-arm64 --output ./publish/linux-musl-arm64/ --self-contained true
       dotnet publish -c Release -r linux-musl-x64 --output ./publish/linux-musl-x64/ --self-contained true
       rm -rf ./publish/*/testcase-validator.pdb
       rm -rf ./publish/*/testcase-validator.xml
       mv ./publish/win-x64/testcase-validator.exe ./publish/win-x64/testcase-validator-win-x64.exe
       mv ./publish/win-x86/testcase-validator.exe ./publish/win-x86/testcase-validator-win-x86.exe
       mv ./publish/win-arm64/testcase-validator.exe ./publish/win-arm64/testcase-validator-win-arm64.exe
       mv ./publish/osx-x64/testcase-validator ./publish/osx-x64/testcase-validator-osx-x64
       mv ./publish/osx-arm64/testcase-validator ./publish/osx-arm64/testcase-validator-osx-arm64
       mv ./publish/linux-x64/testcase-validator ./publish/linux-x64/testcase-validator-linux-x64
       mv ./publish/linux-arm/testcase-validator ./publish/linux-arm/testcase-validator-linux-arm
       mv ./publish/linux-arm64/testcase-validator ./publish/linux-arm64/testcase-validator-linux-arm64
       mv ./publish/linux-musl-arm64/testcase-validator ./publish/linux-musl-arm64/testcase-validator-linux-musl-arm64
       mv ./publish/linux-musl-x64/testcase-validator ./publish/linux-musl-x64/testcase-validator-linux-musl-x64
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "${{ github.sha }}"
        prerelease: true
        title: "testcase-validator"
        files: |
          LICENSE
          publish/*/testcase-validator*
